name: Notify

on:
  schedule:
    - cron: 40 11 * * * # 6:40 PM in Vietnam

jobs:
  update-data:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: install python packages
        run: |
          pip install -r requirements.txt

      - name: notify
        run: python main.py
